# configs/experiment/config.yaml

# This tells Hydra which "knobs" to use by default.
# We're telling it to use the settings in this file, plus the
# specific settings from the 'sisf_full_system' experiment file.
defaults:
  - _self_
  - experiment: sisf_full_system

# Paths to our datasets, which will be tracked by DVC
data:
  adversarial_path: "data/processed/advbench_subset.csv"
  benign_path: "data/processed/hh_rlhf_subset.csv"

# General parameters for all experiments
num_prompts_to_test: 520 # How many prompts to evaluate from each dataset
output_dir: "outputs"     # A folder where all our raw CSV results will be saved